"""Add example field to VocabularyItem

Revision ID: 3878cd69f5c2
Revises: de600f8e3ca7
Create Date: 2024-08-27 15:27:00.302631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3878cd69f5c2'
down_revision = 'de600f8e3ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_item', schema=None) as batch_op:
        batch_op.drop_column('example')

    # ### end Alembic commands ###
