"""Add explanation to VocabularyItem

Revision ID: ade8a397a265
Revises: 3878cd69f5c2
Create Date: 2024-08-27 21:52:01.218001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade8a397a265'
down_revision = '3878cd69f5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))
        batch_op.drop_column('example')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example', sa.TEXT(), nullable=True))
        batch_op.drop_column('explanation')

    # ### end Alembic commands ###
